language: java
os: linux
dist: jammy
jdk:
    - openjdk17
addons:
    sonarcloud:
        organization: "kxsystems"
        token: "$SONAR_KEY"
script:
    - mvn clean verify sonar:sonar -Dsonar.projectKey=KxSystems_javakdb
